name: tensorflow
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.8.1=py37_0
  - asn1crypto=1.2.0=py37_0
  - astor=0.8.0=py37_0
  - astroid=2.3.3=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h7a1dbc1_0
  - cfitsio=3.470=he774522_2
  - chardet=3.0.4=py37_1003
  - colorama=0.4.1=py37_0
  - cryptography=2.8=py37h7a1dbc1_0
  - curl=7.67.0=h2a8f88b_0
  - cycler=0.10.0=py37_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.5=he025d50_0
  - freetype=2.9.1=ha9979f8_1
  - freexl=1.0.5=hfa6e2cd_0
  - gast=0.2.2=py37_0
  - gdal=3.0.2=py37hdf43c64_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.5.1=h5770a2b_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - importlib_metadata=1.1.0=py37_0
  - intel-openmp=2019.4=245
  - ipykernel=5.1.3=py37h39e3cac_0
  - ipython=7.9.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.1=py37_0
  - kealib=1.4.7=h07cbb95_6
  - keras=2.2.4=0
  - keras-applications=1.0.8=py_0
  - keras-base=2.2.4=py37_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37ha925a31_0
  - krb5=1.16.1=hc04afaa_7
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libboost=1.67.0=hd9e427e_4
  - libcurl=7.67.0=h2a8f88b_0
  - libgdal=3.0.2=h1155b67_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libmklml=2019.0.5=0
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libprotobuf=3.10.1=h7bd577a_0
  - libsodium=1.0.16=h9d3ae62_0
  - libspatialite=4.3.0a=h7ffb84d_0
  - libssh2=1.8.2=h7a1dbc1_0
  - libtiff=4.1.0=h56a325e_0
  - libxml2=2.9.9=h464c3ec_0
  - lz4-c=1.8.1.2=h2fa13f4_0
  - m2w64-expat=2.1.1=2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gettext=0.19.7=2
  - m2w64-gmp=6.1.0=2
  - m2w64-libiconv=1.14=6
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-xz=5.2.2=2
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.1.1=py37hc8f65d3_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - more-itertools=7.2.0=py37_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py37_0
  - nbformat=4.4.0=py37_0
  - notebook=6.0.2=py37_0
  - numpy=1.17.4=py37h4320e6b_0
  - numpy-base=1.17.4=py37hc3f5095_0
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.1.1d=he774522_3
  - opt_einsum=3.1.0=py_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - pcre=8.43=ha925a31_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - postgresql=11.2=h3235a2c_0
  - proj=6.2.1=h9f7ef89_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - protobuf=3.10.1=py37h33f27b4_0
  - pycparser=2.19=py37_0
  - pygments=2.5.2=py_0
  - pylint=2.4.4=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.5=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.15.6=py37he774522_0
  - pysocks=1.7.1=py37_0
  - python=3.7.5=h8c8aaf0_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywin32=223=py37hfa6e2cd_1
  - pywinpty=0.5.5=py37_1000
  - pyyaml=5.1.2=py37he774522_0
  - pyzmq=18.1.0=py37ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - requests=2.22.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=42.0.1=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=he774522_0
  - tbb=2018.0.5=he980bc4_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=1.15.0=mkl_py37h3789bd0_0
  - tensorflow-base=1.15.0=mkl_py37h190a33d_0
  - tensorflow-estimator=1.15.1=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tiledb=1.6.3=h7b000aa_0
  - tk=8.6.8=hfa6e2cd_0
  - tornado=6.0.3=py37he774522_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.24.2=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37he774522_0
  - xerces-c=3.2.2=ha925a31_0
  - xz=5.2.4=h2fa13f4_4
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - cftime==1.0.4.2
    - deprecation==2.0.7
    - netcdf4==1.5.3
    - packaging==19.2
    - pandas==0.25.3
    - scipy==1.3.1
    - semver==2.9.0
    - wradlib==1.5.0
    - xarray==0.14.1
    - xmltodict==0.12.0
prefix: C:\Users\lang_m13\AppData\Local\Continuum\miniconda3\envs\tensorflow

